language: swift
osx_image: xcode9.4.1
install:
  - bundle install --without=documentation
  - bundle exec pod repo update
  - bundle exec pod install
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
